<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBEOUcSK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBEOUcSK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBEOUcSK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBEOUcSK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBEOUcSK\App_KernelDevDebugContainer([
    'container.build_hash' => 'BEOUcSK',
    'container.build_id' => 'afc3238c',
    'container.build_time' => 1765803944,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBEOUcSK');
