<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CzIXrqfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.czIXrqf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.czIXrqf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'security.event_dispatcher.pimcore_webdav' => ['privates', 'debug.security.event_dispatcher.pimcore_webdav', 'getDebug_Security_EventDispatcher_PimcoreWebdavService', false],
            'security.event_dispatcher.pimcore_admin' => ['privates', 'debug.security.event_dispatcher.pimcore_admin', 'getDebug_Security_EventDispatcher_PimcoreAdminService', false],
        ], [
            'event_dispatcher' => '?',
            'security.event_dispatcher.pimcore_webdav' => '?',
            'security.event_dispatcher.pimcore_admin' => '?',
        ]);
    }
}
