<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ls0TEQLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ls0TEQL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ls0TEQL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'workflowRegistry' => ['privates', 'workflow.registry', 'getWorkflow_RegistryService', true],
            'workflowManager' => ['services', 'Pimcore\\Workflow\\Manager', 'getManagerService', true],
        ], [
            'workflowRegistry' => '?',
            'workflowManager' => 'Pimcore\\Workflow\\Manager',
        ]);
    }
}
