<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U2t7XTIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U2t7XTI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U2t7XTI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'staticPageGenerator' => ['services', 'Pimcore\\Document\\StaticPageGenerator', 'getStaticPageGeneratorService', false],
        ], [
            'staticPageGenerator' => 'Pimcore\\Document\\StaticPageGenerator',
        ]);
    }
}
