<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BnC_KZu_KernelregisterBundlesToCollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BnC.kZu.kernel::registerBundlesToCollection()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BnC.kZu.kernel::registerBundlesToCollection()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'collection' => ['privates', '.errored..service_locator.BnC.kZu.Pimcore\\HttpKernel\\BundleCollection\\BundleCollection', NULL, 'Cannot autowire service ".service_locator.BnC.kZu": it references class "Pimcore\\HttpKernel\\BundleCollection\\BundleCollection" but no such service exists.'],
        ], [
            'collection' => 'Pimcore\\HttpKernel\\BundleCollection\\BundleCollection',
        ]))->withContext('kernel::registerBundlesToCollection()', $container);
    }
}
