<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetHelperControllergetSharedGridColumnConfigsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Am00ba4.Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetHelperController::getSharedGridColumnConfigs()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Am00ba4.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Asset\\AssetHelperController::getSharedGridColumnConfigs()'] = ($container->privates['.service_locator.Am00ba4'] ?? $container->load('get_ServiceLocator_Am00ba4Service'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Asset\\AssetHelperController::getSharedGridColumnConfigs()', $container);
    }
}
