<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllergetDataProvidersActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XHmUEb2.Pimcore\Bundle\AdminBundle\Controller\GDPR\AdminController::getDataProvidersAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XHmUEb2.Pimcore\\Bundle\\AdminBundle\\Controller\\GDPR\\AdminController::getDataProvidersAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['privates', 'Pimcore\\Bundle\\AdminBundle\\GDPR\\DataProvider\\Manager', 'getManager2Service', true],
        ], [
            'manager' => 'Pimcore\\Bundle\\AdminBundle\\GDPR\\DataProvider\\Manager',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\GDPR\\AdminController::getDataProvidersAction()', $container);
    }
}
