<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetControllerdeleteInfoActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9MgD4IO.Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController::deleteInfoAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.9MgD4IO'] ?? $container->load('get_ServiceLocator_9MgD4IOService'));

        if (isset($container->privates['.service_locator.9MgD4IO.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Asset\\AssetController::deleteInfoAction()'])) {
            return $container->privates['.service_locator.9MgD4IO.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Asset\\AssetController::deleteInfoAction()'];
        }

        return $container->privates['.service_locator.9MgD4IO.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Asset\\AssetController::deleteInfoAction()'] = $a->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Asset\\AssetController::deleteInfoAction()', $container);
    }
}
