<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddToUpdateTaskQueueCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\Asset\AddToUpdateTaskQueueCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\Asset\AddToUpdateTaskQueueCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/Asset/AddToUpdateTaskQueueCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\Asset\\AddToUpdateTaskQueueCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\Asset\AddToUpdateTaskQueueCommand();

        $instance->setName('pimcore:assets:add-to-update-task-queue');
        $instance->setAliases(['pimcore:assets:add-to-update-task-queue']);
        $instance->setDescription('Adds assets to update task queue for re-processing (previews, meta-data, ...)');

        return $instance;
    }
}
