<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetControllershowVersionActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.01sAJz9.Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController::showVersionAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.01sAJz9'] ?? $container->load('get_ServiceLocator_01sAJz9Service'));

        if (isset($container->privates['.service_locator.01sAJz9.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Asset\\AssetController::showVersionAction()'])) {
            return $container->privates['.service_locator.01sAJz9.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Asset\\AssetController::showVersionAction()'];
        }

        return $container->privates['.service_locator.01sAJz9.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Asset\\AssetController::showVersionAction()'] = $a->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Asset\\AssetController::showVersionAction()', $container);
    }
}
