<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddToUpdateTaskQueueCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Pimcore\Bundle\CoreBundle\Command\Asset\AddToUpdateTaskQueueCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Pimcore\\Bundle\\CoreBundle\\Command\\Asset\\AddToUpdateTaskQueueCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pimcore:assets:add-to-update-task-queue', ['pimcore:assets:add-to-update-task-queue'], 'Adds assets to update task queue for re-processing (previews, meta-data, ...)', false, #[\Closure(name: 'Pimcore\\Bundle\\CoreBundle\\Command\\Asset\\AddToUpdateTaskQueueCommand')] fn (): \Pimcore\Bundle\CoreBundle\Command\Asset\AddToUpdateTaskQueueCommand => ($container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\Asset\\AddToUpdateTaskQueueCommand'] ?? $container->load('getAddToUpdateTaskQueueCommandService')));
    }
}
