<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetControllerexportAssetsActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._BinBm6.Pimcore\Bundle\AdminBundle\Controller\GDPR\AssetController::exportAssetsAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._BinBm6.Pimcore\\Bundle\\AdminBundle\\Controller\\GDPR\\AssetController::exportAssetsAction()'] = ($container->privates['.service_locator._BinBm6'] ?? $container->load('get_ServiceLocator_BinBm6Service'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\GDPR\\AssetController::exportAssetsAction()', $container);
    }
}
