<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsoleCommandListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\EventListener\ConsoleCommandListener' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\EventListener\ConsoleCommandListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/EventListener/ConsoleCommandListener.php';

        return $container->privates['Pimcore\\Bundle\\CoreBundle\\EventListener\\ConsoleCommandListener'] = new \Pimcore\Bundle\CoreBundle\EventListener\ConsoleCommandListener(($container->privates['Pimcore\\Console\\CommandContextHolder'] ??= new \Pimcore\Console\CommandContextHolder()));
    }
}
