<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassControllerobjectbrickListActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9MgD4IO.Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassController::objectbrickListAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9MgD4IO.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\ClassController::objectbrickListAction()'] = ($container->privates['.service_locator.9MgD4IO'] ?? $container->load('get_ServiceLocator_9MgD4IOService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\ClassController::objectbrickListAction()', $container);
    }
}
