<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassesDefinitionsChangesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsChangesCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsChangesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/ClassesDefinitionsChangesCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Model/DataObject/ClassDefinition/ClassDefinitionManager.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\ClassesDefinitionsChangesCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsChangesCommand(($container->services['Pimcore\\Model\\DataObject\\ClassDefinition\\ClassDefinitionManager'] ??= new \Pimcore\Model\DataObject\ClassDefinition\ClassDefinitionManager()));

        $instance->setName('pimcore:classes:changes');
        $instance->setAliases(['pimcore:classes:changes']);
        $instance->setDescription('outputs the classes that have changes in their definition files');

        return $instance;
    }
}
