<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataObjectControlleraddActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yb__cmb.Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController::addAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yb__cmb.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\DataObjectController::addAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'modelFactory' => ['services', 'pimcore.model.factory', 'getPimcore_Model_FactoryService', true],
        ], [
            'modelFactory' => '?',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\DataObjectController::addAction()', $container);
    }
}
