<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataObjectControllergetActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w8V1eE4.Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController::getAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w8V1eE4.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\DataObjectController::getAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'defaultPreviewGenerator' => ['privates', 'Pimcore\\Model\\DataObject\\ClassDefinition\\PreviewGeneratorInterface', 'getPreviewGeneratorInterfaceService', true],
        ], [
            'eventDispatcher' => '?',
            'defaultPreviewGenerator' => 'Pimcore\\Model\\DataObject\\ClassDefinition\\PreviewGeneratorInterface',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\DataObjectController::getAction()', $container);
    }
}
