<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataObjectHelperControllergetExportJobsActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hBBUWmC.Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController::getExportJobsAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hBBUWmC.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\DataObjectHelperController::getExportJobsAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gridHelperService' => ['privates', 'Pimcore\\Bundle\\AdminBundle\\Helper\\GridHelperService', 'getGridHelperServiceService', true],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
        ], [
            'gridHelperService' => 'Pimcore\\Bundle\\AdminBundle\\Helper\\GridHelperService',
            'eventDispatcher' => '?',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\DataObjectHelperController::getExportJobsAction()', $container);
    }
}
