<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_Security_Authenticator_TwoFactor_PimcoreAdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.security.authenticator.two_factor.pimcore_admin' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/InteractiveAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-bundle/Security/Http/Authenticator/TwoFactorAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Util/TargetPathTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-bundle/Security/Http/Authentication/DefaultAuthenticationSuccessHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticationFailureHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-bundle/Security/Http/Authentication/DefaultAuthenticationFailureHandler.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['debug.security.authenticator.two_factor.pimcore_admin'])) {
            return $container->privates['debug.security.authenticator.two_factor.pimcore_admin'];
        }
        $b = ($container->privates['security.firewall_config.two_factor.pimcore_admin'] ?? self::getSecurity_FirewallConfig_TwoFactor_PimcoreAdminService($container));
        $c = ($container->privates['security.http_utils'] ?? self::getSecurity_HttpUtilsService($container));

        return $container->privates['debug.security.authenticator.two_factor.pimcore_admin'] = new \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator(new \Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator($b, ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), new \Scheb\TwoFactorBundle\Security\Http\Authentication\DefaultAuthenticationSuccessHandler($c, $b), new \Scheb\TwoFactorBundle\Security\Http\Authentication\DefaultAuthenticationFailureHandler($c, $b), ($container->privates['security.authentication.authentication_required_handler.two_factor.pimcore_admin'] ?? $container->load('getSecurity_Authentication_AuthenticationRequiredHandler_TwoFactor_PimcoreAdminService')), $a, ($container->services['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container))));
    }
}
