<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataObjectHelperControllerdownloadXlsxFileActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MsrU.ep.Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController::downloadXlsxFileAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MsrU.ep.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\DataObjectHelperController::downloadXlsxFileAction()'] = ($container->privates['.service_locator.MsrU.ep'] ?? $container->load('get_ServiceLocator_MsrU_EpService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\DataObjectHelperController::downloadXlsxFileAction()', $container);
    }
}
