<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataObjectHelperControllerdoExportActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.irIIC6R.Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController::doExportAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.irIIC6R.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\DataObjectHelperController::doExportAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'localeService' => ['services', 'Pimcore\\Localization\\LocaleServiceInterface', 'getLocaleServiceInterfaceService', false],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
        ], [
            'localeService' => 'Pimcore\\Localization\\LocaleServiceInterface',
            'eventDispatcher' => '?',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\DataObjectHelperController::doExportAction()', $container);
    }
}
