<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailControllershowEmailLogActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZU1NPq5.Pimcore\Bundle\AdminBundle\Controller\Admin\EmailController::showEmailLogAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZU1NPq5.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\EmailController::showEmailLogAction()'] = ($container->privates['.service_locator.ZU1NPq5'] ?? $container->load('get_ServiceLocator_ZU1NPq5Service'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\EmailController::showEmailLogAction()', $container);
    }
}
