<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerindexActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FFPTIRK.Pimcore\Bundle\AdminBundle\Controller\Admin\IndexController::indexAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FFPTIRK.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\IndexController::indexAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel' => ['services', 'kernel', 'getKernelService', false],
            'maintenanceExecutor' => ['privates', 'Pimcore\\Maintenance\\Executor', 'getExecutorService', true],
            'csrfProtection' => ['services', 'Pimcore\\Bundle\\AdminBundle\\Security\\CsrfProtectionHandler', 'getCsrfProtectionHandlerService', false],
            'config' => ['services', 'Pimcore\\Config', 'getConfigService', false],
            'bundleManager' => ['services', 'Pimcore\\Extension\\Bundle\\PimcoreBundleManager', 'getPimcoreBundleManagerService', false],
            'maintenanceModeHelper' => ['services', 'Pimcore\\Tool\\MaintenanceModeHelperInterface', 'getMaintenanceModeHelperInterfaceService', false],
        ], [
            'kernel' => '?',
            'maintenanceExecutor' => 'Pimcore\\Maintenance\\Executor',
            'csrfProtection' => 'Pimcore\\Bundle\\AdminBundle\\Security\\CsrfProtectionHandler',
            'config' => 'Pimcore\\Config',
            'bundleManager' => 'Pimcore\\Extension\\Bundle\\PimcoreBundleManager',
            'maintenanceModeHelper' => 'Pimcore\\Tool\\MaintenanceModeHelperInterface',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\IndexController::indexAction()', $container);
    }
}
