<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControlleronKernelResponseEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nH8gSdl.Pimcore\Bundle\AdminBundle\Controller\Admin\IndexController::onKernelResponseEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nH8gSdl.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\IndexController::onKernelResponseEvent()'] = ($container->privates['.service_locator.nH8gSdl'] ?? $container->load('get_ServiceLocator_NH8gSdlService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\IndexController::onKernelResponseEvent()', $container);
    }
}
