<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallControllercheckActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3_iFdS6.Pimcore\Bundle\AdminBundle\Controller\Admin\InstallController::checkAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3_iFdS6.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\InstallController::checkAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'db' => ['services', 'doctrine.dbal.default_connection', 'getDoctrine_Dbal_DefaultConnectionService', false],
            'profiler' => ['services', '.container.private.profiler', 'get_Container_Private_ProfilerService', false],
        ], [
            'db' => '?',
            'profiler' => '?',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\InstallController::checkAction()', $container);
    }
}
