<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginControllerlostpasswordActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._kNH5l_.Pimcore\Bundle\AdminBundle\Controller\Admin\LoginController::lostpasswordAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._kNH5l_.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\LoginController::lostpasswordAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfProtection' => ['services', 'Pimcore\\Bundle\\AdminBundle\\Security\\CsrfProtectionHandler', 'getCsrfProtectionHandlerService', false],
            'config' => ['services', 'Pimcore\\Config', 'getConfigService', false],
            'resetPasswordLimiter' => ['privates', 'limiter.reset_password', 'getLimiter_ResetPasswordService', true],
            'router' => ['services', 'router', 'getRouterService', false],
        ], [
            'csrfProtection' => 'Pimcore\\Bundle\\AdminBundle\\Security\\CsrfProtectionHandler',
            'config' => 'Pimcore\\Config',
            'resetPasswordLimiter' => '?',
            'router' => '?',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\LoginController::lostpasswordAction()', $container);
    }
}
