<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkControllergetDataByIdActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0j4henY.Pimcore\Bundle\AdminBundle\Controller\Admin\Document\LinkController::getDataByIdAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0j4henY.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\LinkController::getDataByIdAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'serializer', 'getSerializer2Service', false],
        ], [
            'serializer' => '?',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\LinkController::getDataByIdAction()', $container);
    }
}
