<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkControlleronKernelControllerEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FPHItPV.Pimcore\Bundle\AdminBundle\Controller\Admin\Document\LinkController::onKernelControllerEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FPHItPV.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\LinkController::onKernelControllerEvent()'] = ($container->privates['.service_locator.FPHItPV'] ?? $container->load('get_ServiceLocator_FPHItPVService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\LinkController::onKernelControllerEvent()', $container);
    }
}
