<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginControllertwoFactorSetupAuthenticationActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kAdCkpP.Pimcore\Bundle\AdminBundle\Controller\Admin\LoginController::twoFactorSetupAuthenticationAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kAdCkpP.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\LoginController::twoFactorSetupAuthenticationAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'config' => ['services', 'Pimcore\\Config', 'getConfigService', false],
            'twoFactor' => ['services', 'scheb_two_factor.security.google_authenticator', 'getSchebTwoFactor_Security_GoogleAuthenticatorService', true],
        ], [
            'config' => 'Pimcore\\Config',
            'twoFactor' => '?',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\LoginController::twoFactorSetupAuthenticationAction()', $container);
    }
}
