<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginControllerloginActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VZUfg.s.Pimcore\Bundle\AdminBundle\Controller\Admin\LoginController::loginAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VZUfg.s.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\LoginController::loginAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'csrfProtection' => ['services', 'Pimcore\\Bundle\\AdminBundle\\Security\\CsrfProtectionHandler', 'getCsrfProtectionHandlerService', false],
            'config' => ['services', 'Pimcore\\Config', 'getConfigService', false],
        ], [
            'authenticationUtils' => '?',
            'csrfProtection' => 'Pimcore\\Bundle\\AdminBundle\\Security\\CsrfProtectionHandler',
            'config' => 'Pimcore\\Config',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\LoginController::loginAction()', $container);
    }
}
