<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginControllercsrfTokenActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xpHugnl.Pimcore\Bundle\AdminBundle\Controller\Admin\LoginController::csrfTokenAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xpHugnl.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\LoginController::csrfTokenAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfProtection' => ['services', 'Pimcore\\Bundle\\AdminBundle\\Security\\CsrfProtectionHandler', 'getCsrfProtectionHandlerService', false],
        ], [
            'csrfProtection' => 'Pimcore\\Bundle\\AdminBundle\\Security\\CsrfProtectionHandler',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\LoginController::csrfTokenAction()', $container);
    }
}
