<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Bus_Pimcorecore_Middleware_HandleMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.bus.pimcore-core.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        $container->privates['messenger.bus.pimcore-core.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Symfony\\Component\\Process\\Messenger\\RunProcessMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.jsEzfAf'] ?? $container->load('get_Messenger_HandlerDescriptor_JsEzfAfService'));
        }, 1), 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.VzfZOmE'] ?? $container->load('get_Messenger_HandlerDescriptor_VzfZOmEService'));
        }, 1), 'Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.TRXHuMU'] ?? $container->load('get_Messenger_HandlerDescriptor_TRXHuMUService'));
        }, 1), 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.vzDzyJR'] ?? $container->load('get_Messenger_HandlerDescriptor_VzDzyJRService'));
        }, 1), 'Pimcore\\Bundle\\SimpleBackendSearchBundle\\Message\\SearchBackendMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.z2eW7G9'] ?? $container->load('get_Messenger_HandlerDescriptor_Z2eW7G9Service'));
        }, 1), 'Pimcore\\Messenger\\VideoConvertMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.GvdMpfF'] ?? $container->load('get_Messenger_HandlerDescriptor_GvdMpfFService'));
        }, 1), 'Pimcore\\Messenger\\CleanupThumbnailsMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.GbSnA09'] ?? $container->load('get_Messenger_HandlerDescriptor_GbSnA09Service'));
        }, 1), 'Pimcore\\Messenger\\AssetUpdateTasksMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.l8SiZl1'] ?? $container->load('get_Messenger_HandlerDescriptor_L8SiZl1Service'));
        }, 1), 'Pimcore\\Messenger\\AssetPreviewImageMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.G_Shzbn'] ?? $container->load('get_Messenger_HandlerDescriptor_GShzbnService'));
        }, 1), 'Pimcore\\Messenger\\MaintenanceTaskMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.9tIVoMA'] ?? $container->load('get_Messenger_HandlerDescriptor_9tIVoMAService'));
        }, 1), 'Pimcore\\Messenger\\ScheduledTaskMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.htgs2Pq'] ?? $container->load('get_Messenger_HandlerDescriptor_Htgs2PqService'));
        }, 1), 'Pimcore\\Messenger\\OptimizeImageMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.ehfT22F'] ?? $container->load('get_Messenger_HandlerDescriptor_EhfT22FService'));
        }, 1), 'Pimcore\\Messenger\\GeneratePagePreviewMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.W_SNkEr'] ?? $container->load('get_Messenger_HandlerDescriptor_WSNkErService'));
        }, 1), 'Pimcore\\Messenger\\VersionDeleteMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.kuQjcSo'] ?? $container->load('get_Messenger_HandlerDescriptor_KuQjcSoService'));
        }, 1), 'Pimcore\\Messenger\\SanityCheckMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.jz70v.b'] ?? $container->load('get_Messenger_HandlerDescriptor_Jz70v_BService'));
        }, 1), 'Pimcore\\Messenger\\ElementDependenciesMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.V98w6m7'] ?? $container->load('get_Messenger_HandlerDescriptor_V98w6m7Service'));
        }, 1)]), false);

        if ($container->has('monolog.logger.messenger')) {
            $instance->setLogger(($container->services['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));
        }

        return $instance;
    }
}
