<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMiscControllerjsonTranslationsSystemActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.51hHbbT.Pimcore\Bundle\AdminBundle\Controller\Admin\MiscController::jsonTranslationsSystemAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.51hHbbT.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\MiscController::jsonTranslationsSystemAction()'] = ($container->privates['.service_locator.51hHbbT'] ?? $container->load('get_ServiceLocator_51hHbbTService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\MiscController::jsonTranslationsSystemAction()', $container);
    }
}
