<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailLogsFolderStructureCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Pimcore\Bundle\CoreBundle\Command\Migrate\MailLogsFolderStructureCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Pimcore\\Bundle\\CoreBundle\\Command\\Migrate\\MailLogsFolderStructureCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pimcore:migrate:mail-logs-folder-structure', ['pimcore:migrate:mail-logs-folder-structure'], 'Change mail logs folder structure to'."\n".'    YYYY/MM/DD/<log filename>'."\n".'    instead of'."\n".'    <log filename>', false, #[\Closure(name: 'Pimcore\\Bundle\\CoreBundle\\Command\\Migrate\\MailLogsFolderStructureCommand')] fn (): \Pimcore\Bundle\CoreBundle\Command\Migrate\MailLogsFolderStructureCommand => ($container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\Migrate\\MailLogsFolderStructureCommand'] ?? $container->load('getMailLogsFolderStructureCommandService')));
    }
}
