<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMiscControllercountryListActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tLqHyBl.Pimcore\Bundle\AdminBundle\Controller\Admin\MiscController::countryListAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tLqHyBl.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\MiscController::countryListAction()'] = ($container->privates['.service_locator.tLqHyBl'] ?? $container->load('get_ServiceLocator_TLqHyBlService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\MiscController::countryListAction()', $container);
    }
}
