<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMiscControllermaintenanceActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8HDFBv2.Pimcore\Bundle\AdminBundle\Controller\Admin\MiscController::maintenanceAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8HDFBv2.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\MiscController::maintenanceAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'maintenanceModeHelper' => ['services', 'Pimcore\\Tool\\MaintenanceModeHelperInterface', 'getMaintenanceModeHelperInterfaceService', false],
        ], [
            'maintenanceModeHelper' => 'Pimcore\\Tool\\MaintenanceModeHelperInterface',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\MiscController::maintenanceAction()', $container);
    }
}
