<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Middleware_DeduplicateMiddlewareService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.middleware.deduplicate_middleware' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\DeduplicateMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/DeduplicateMiddleware.php';

        return $container->privates['messenger.middleware.deduplicate_middleware'] = new \Symfony\Component\Messenger\Middleware\DeduplicateMiddleware(($container->privates['lock.default.factory'] ?? $container->load('getLock_Default_FactoryService')));
    }
}
