<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailLogsFolderStructureCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\Migrate\MailLogsFolderStructureCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\Migrate\MailLogsFolderStructureCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/Migrate/MailLogsFolderStructureCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\Migrate\\MailLogsFolderStructureCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\Migrate\MailLogsFolderStructureCommand();

        $instance->setName('pimcore:migrate:mail-logs-folder-structure');
        $instance->setAliases(['pimcore:migrate:mail-logs-folder-structure']);
        $instance->setDescription('Change mail logs folder structure to'."\n".'    YYYY/MM/DD/<log filename>'."\n".'    instead of'."\n".'    <log filename>');

        return $instance;
    }
}
