<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllerfindAllActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vaOFqMr.Pimcore\Bundle\AdminBundle\Controller\Admin\NotificationController::findAllAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vaOFqMr.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\NotificationController::findAllAction()'] = ($container->privates['.service_locator.vaOFqMr'] ?? $container->load('get_ServiceLocator_VaOFqMrService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\NotificationController::findAllAction()', $container);
    }
}
