<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageControllergetDataByIdActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U2t7XTI.Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController::getDataByIdAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.U2t7XTI'] ?? $container->load('get_ServiceLocator_U2t7XTIService'));

        if (isset($container->privates['.service_locator.U2t7XTI.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\PageController::getDataByIdAction()'])) {
            return $container->privates['.service_locator.U2t7XTI.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\PageController::getDataByIdAction()'];
        }

        return $container->privates['.service_locator.U2t7XTI.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\PageController::getDataByIdAction()'] = $a->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\PageController::getDataByIdAction()', $container);
    }
}
