<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageControllersaveActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U2t7XTI.Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController::saveAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U2t7XTI.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\PageController::saveAction()'] = ($container->privates['.service_locator.U2t7XTI'] ?? $container->load('get_ServiceLocator_U2t7XTIService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\PageController::saveAction()', $container);
    }
}
