<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageControllerareabrickRenderIndexEditmodeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J5LF1.f.Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController::areabrickRenderIndexEditmode()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J5LF1.f.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\PageController::areabrickRenderIndexEditmode()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blockStateStack' => ['services', 'Pimcore\\Document\\Editable\\Block\\BlockStateStack', 'getBlockStateStackService', false],
            'definitionCollector' => ['privates', 'Pimcore\\Document\\Editable\\EditmodeEditableDefinitionCollector', 'getEditmodeEditableDefinitionCollectorService', false],
            'twig' => ['privates', 'twig', 'getTwigService', false],
            'editableRenderer' => ['services', 'Pimcore\\Templating\\Renderer\\EditableRenderer', 'getEditableRendererService', false],
            'documentResolver' => ['services', 'Pimcore\\Http\\Request\\Resolver\\DocumentResolver', 'getDocumentResolverService', false],
            'localeService' => ['services', 'Pimcore\\Localization\\LocaleServiceInterface', 'getLocaleServiceInterfaceService', false],
        ], [
            'blockStateStack' => 'Pimcore\\Document\\Editable\\Block\\BlockStateStack',
            'definitionCollector' => 'Pimcore\\Document\\Editable\\EditmodeEditableDefinitionCollector',
            'twig' => '?',
            'editableRenderer' => 'Pimcore\\Templating\\Renderer\\EditableRenderer',
            'documentResolver' => 'Pimcore\\Http\\Request\\Resolver\\DocumentResolver',
            'localeService' => 'Pimcore\\Localization\\LocaleServiceInterface',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\PageController::areabrickRenderIndexEditmode()', $container);
    }
}
