<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcore_Templating_Engine_DelegatingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'pimcore.templating.engine.delegating' shared autowired service.
     *
     * @return \Pimcore\Templating\TwigDefaultDelegatingEngine
     *
     * @deprecated Since pimcore/pimcore 12.3: The "pimcore.templating.engine.delegating" service is deprecated and will be removed in 13.0. Inject Twig\Environment directly instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('pimcore/pimcore', '12.3', 'The "pimcore.templating.engine.delegating" service is deprecated and will be removed in 13.0. Inject Twig\\Environment directly instead.');

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->services['pimcore.templating.engine.delegating'])) {
            return $container->services['pimcore.templating.engine.delegating'];
        }

        return $container->services['pimcore.templating.engine.delegating'] = new \Pimcore\Templating\TwigDefaultDelegatingEngine($a, ($container->services['Pimcore\\Config'] ??= new \Pimcore\Config()));
    }
}
