<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcoreUsersControllerexportUserDataActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YMq54yR.Pimcore\Bundle\AdminBundle\Controller\GDPR\PimcoreUsersController::exportUserDataAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YMq54yR.Pimcore\\Bundle\\AdminBundle\\Controller\\GDPR\\PimcoreUsersController::exportUserDataAction()'] = ($container->privates['.service_locator.YMq54yR'] ?? $container->load('get_ServiceLocator_YMq54yRService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\GDPR\\PimcoreUsersController::exportUserDataAction()', $container);
    }
}
