<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageControllergeneratePreviewsActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NeahAQH.Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController::generatePreviewsAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NeahAQH.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\PageController::generatePreviewsAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'messengerBusPimcoreCore' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
        ], [
            'messengerBusPimcoreCore' => '?',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\PageController::generatePreviewsAction()', $container);
    }
}
