<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcore_CalculatedValue_ExpressionLanguageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'pimcore.calculated_value.expression_language' shared autowired service.
     *
     * @return \Pimcore\Helper\SymfonyExpression\CalculatedFieldExpressionLanguage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Helper/SymfonyExpression/CalculatedFieldExpressionLanguage.php';

        return $container->services['pimcore.calculated_value.expression_language'] = new \Pimcore\Helper\SymfonyExpression\CalculatedFieldExpressionLanguage(new RewindableGenerator(fn () => new \EmptyIterator(), 0));
    }
}
