<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuantityValueControllerconvertActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3v7ClNX.Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\QuantityValueController::convertAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3v7ClNX.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\QuantityValueController::convertAction()'] = ($container->privates['.service_locator.3v7ClNX'] ?? $container->load('get_ServiceLocator_3v7ClNXService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\QuantityValueController::convertAction()', $container);
    }
}
