<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenderletControllerrenderletActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9BdXyXb.Pimcore\Bundle\AdminBundle\Controller\Admin\Document\RenderletController::renderletAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9BdXyXb.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\RenderletController::renderletAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actionRenderer' => ['privates', 'Pimcore\\Templating\\Renderer\\ActionRenderer', 'getActionRendererService', false],
            'editableHandler' => ['services', 'Pimcore\\Document\\Editable\\EditableHandler', 'getEditableHandlerService', true],
            'localeService' => ['services', 'Pimcore\\Localization\\LocaleServiceInterface', 'getLocaleServiceInterfaceService', false],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
        ], [
            'actionRenderer' => 'Pimcore\\Templating\\Renderer\\ActionRenderer',
            'editableHandler' => 'Pimcore\\Document\\Editable\\EditableHandler',
            'localeService' => 'Pimcore\\Localization\\LocaleServiceInterface',
            'eventDispatcher' => '?',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\RenderletController::renderletAction()', $container);
    }
}
