<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsControllersetAppearanceSystemActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9YprJmz.Pimcore\Bundle\AdminBundle\Controller\Admin\SettingsController::setAppearanceSystemAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9YprJmz.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::setAppearanceSystemAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel' => ['services', 'kernel', 'getKernelService', false],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'cache' => ['services', 'Pimcore\\Cache\\Core\\CoreCacheHandler', 'getCoreCacheHandlerService', true],
            'filesystem' => ['privates', 'filesystem', 'getFilesystemService', true],
            'symfonyCacheClearer' => ['services', 'Pimcore\\Cache\\Symfony\\CacheClearer', 'getCacheClearerService', true],
            'config' => ['privates', 'Pimcore\\Bundle\\AdminBundle\\System\\AdminConfig', 'getAdminConfigService', true],
        ], [
            'kernel' => '?',
            'eventDispatcher' => '?',
            'cache' => 'Pimcore\\Cache\\Core\\CoreCacheHandler',
            'filesystem' => '?',
            'symfonyCacheClearer' => 'Pimcore\\Cache\\Symfony\\CacheClearer',
            'config' => 'Pimcore\\Bundle\\AdminBundle\\System\\AdminConfig',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::setAppearanceSystemAction()', $container);
    }
}
