<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSnippetControllergetTreeNodeConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7fukyOq.Pimcore\Bundle\AdminBundle\Controller\Admin\Document\SnippetController::getTreeNodeConfig()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7fukyOq.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\SnippetController::getTreeNodeConfig()'] = ($container->privates['.service_locator.7fukyOq'] ?? $container->load('get_ServiceLocator_7fukyOqService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\Document\\SnippetController::getTreeNodeConfig()', $container);
    }
}
