<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsControllergetSystemActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2AmXje0.Pimcore\Bundle\AdminBundle\Controller\Admin\SettingsController::getSystemAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2AmXje0.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::getSystemAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'config' => ['services', 'Pimcore\\SystemSettingsConfig', 'getSystemSettingsConfigService', false],
        ], [
            'config' => 'Pimcore\\SystemSettingsConfig',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::getSystemAction()', $container);
    }
}
