<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsControllerclearTemporaryFilesActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._m7E.a3.Pimcore\Bundle\AdminBundle\Controller\Admin\SettingsController::clearTemporaryFilesAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._m7E.a3.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::clearTemporaryFilesAction()'] = ($container->privates['.service_locator._m7E.a3'] ?? $container->load('get_ServiceLocator_M7E_A3Service'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::clearTemporaryFilesAction()', $container);
    }
}
