<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticsControllerstatisticsActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TLMxz2f.Pimcore\Bundle\CoreBundle\Controller\StatisticsController::statisticsAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TLMxz2f.Pimcore\\Bundle\\CoreBundle\\Controller\\StatisticsController::statisticsAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'statisticsManager' => ['privates', 'Pimcore\\Tool\\StatisticsManager', 'getStatisticsManagerService', true],
        ], [
            'statisticsManager' => 'Pimcore\\Tool\\StatisticsManager',
        ]))->withContext('Pimcore\\Bundle\\CoreBundle\\Controller\\StatisticsController::statisticsAction()', $container);
    }
}
