<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsControllergetAppearanceSystemActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JK18UtA.Pimcore\Bundle\AdminBundle\Controller\Admin\SettingsController::getAppearanceSystemAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JK18UtA.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::getAppearanceSystemAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'config' => ['privates', 'Pimcore\\Bundle\\AdminBundle\\System\\AdminConfig', 'getAdminConfigService', true],
        ], [
            'config' => 'Pimcore\\Bundle\\AdminBundle\\System\\AdminConfig',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::getAppearanceSystemAction()', $container);
    }
}
