<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchControllerfindActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uNeay8E.Pimcore\Bundle\SimpleBackendSearchBundle\Controller\SearchController::findAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uNeay8E.Pimcore\\Bundle\\SimpleBackendSearchBundle\\Controller\\SearchController::findAction()'] = ($container->privates['.service_locator.uNeay8E'] ?? $container->load('get_ServiceLocator_UNeay8EService'))->withContext('Pimcore\\Bundle\\SimpleBackendSearchBundle\\Controller\\SearchController::findAction()', $container);
    }
}
