<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Command_DebugFirewallService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.command.debug_firewall' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Command/DebugFirewallCommand.php';

        $container->privates['security.command.debug_firewall'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand($container->parameters['security.firewalls'], ($container->privates['.service_locator.xSokMwZ'] ?? self::get_ServiceLocator_XSokMwZService($container)), ($container->privates['.service_locator.czIXrqf'] ?? $container->load('get_ServiceLocator_CzIXrqfService')), ['pimcore_webdav' => [($container->privates['debug.security.authenticator.http_basic.pimcore_webdav'] ?? $container->load('getDebug_Security_Authenticator_HttpBasic_PimcoreWebdavService'))], 'pimcore_admin' => [($container->privates['debug.Pimcore\\Bundle\\AdminBundle\\Security\\Authenticator\\AdminTokenAuthenticator'] ?? $container->load('getAdminTokenAuthenticatorService')), ($container->privates['debug.security.authenticator.two_factor.pimcore_admin'] ?? $container->load('getDebug_Security_Authenticator_TwoFactor_PimcoreAdminService')), ($container->privates['debug.security.authenticator.form_login.pimcore_admin'] ?? $container->load('getDebug_Security_Authenticator_FormLogin_PimcoreAdminService'))]], false);

        $instance->setName('debug:firewall');
        $instance->setDescription('Display information about your security firewall(s)');

        return $instance;
    }
}
