<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchControllerquickSearchByIdActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2VhlNt3.Pimcore\Bundle\SimpleBackendSearchBundle\Controller\SearchController::quickSearchByIdAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2VhlNt3.Pimcore\\Bundle\\SimpleBackendSearchBundle\\Controller\\SearchController::quickSearchByIdAction()'] = ($container->privates['.service_locator.2VhlNt3'] ?? $container->load('get_ServiceLocator_2VhlNt3Service'))->withContext('Pimcore\\Bundle\\SimpleBackendSearchBundle\\Controller\\SearchController::quickSearchByIdAction()', $container);
    }
}
