<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticsManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Tool\StatisticsManager' shared autowired service.
     *
     * @return \Pimcore\Tool\StatisticsManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Tool/StatisticsManager.php';

        return $container->privates['Pimcore\\Tool\\StatisticsManager'] = new \Pimcore\Tool\StatisticsManager('4qQWf8MKSfYoBNR9SFUA1x', ($container->services['kernel'] ?? $container->get('kernel', 1)), $container->parameters['pimcore.config'], ($container->services['GuzzleHttp\\Client'] ?? $container->load('getClientService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['Pimcore\\Http\\RequestHelper'] ?? self::getRequestHelperService($container)));
    }
}
