<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsControllerclearOutputCacheActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._m7E.a3.Pimcore\Bundle\AdminBundle\Controller\Admin\SettingsController::clearOutputCacheAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator._m7E.a3'] ?? $container->load('get_ServiceLocator_M7E_A3Service'));

        if (isset($container->privates['.service_locator._m7E.a3.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::clearOutputCacheAction()'])) {
            return $container->privates['.service_locator._m7E.a3.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::clearOutputCacheAction()'];
        }

        return $container->privates['.service_locator._m7E.a3.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::clearOutputCacheAction()'] = $a->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\SettingsController::clearOutputCacheAction()', $container);
    }
}
