<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerupdateCurrentUserActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z5nvVNx.Pimcore\Bundle\AdminBundle\Controller\Admin\UserController::updateCurrentUserAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z5nvVNx.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\UserController::updateCurrentUserAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'validator' => '?',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\UserController::updateCurrentUserAction()', $container);
    }
}
