<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVariantsControllergetVariantsActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DmLL1x8.Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\VariantsController::getVariantsAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DmLL1x8.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\VariantsController::getVariantsAction()'] = ($container->privates['.service_locator.DmLL1x8'] ?? $container->load('get_ServiceLocator_DmLL1x8Service'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\DataObject\\VariantsController::getVariantsAction()', $container);
    }
}
