<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflowControllergetModalCustomHtmlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WxTaclX.Pimcore\Bundle\AdminBundle\Controller\Admin\WorkflowController::getModalCustomHtml()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WxTaclX.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\WorkflowController::getModalCustomHtml()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'workflowRegistry' => ['privates', 'workflow.registry', 'getWorkflow_RegistryService', true],
            'manager' => ['services', 'Pimcore\\Workflow\\Manager', 'getManagerService', true],
        ], [
            'workflowRegistry' => '?',
            'manager' => 'Pimcore\\Workflow\\Manager',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\WorkflowController::getModalCustomHtml()', $container);
    }
}
