<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflowControllergetWorkflowDetailsStoreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CM0Znmj.Pimcore\Bundle\AdminBundle\Controller\Admin\WorkflowController::getWorkflowDetailsStore()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CM0Znmj.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\WorkflowController::getWorkflowDetailsStore()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'workflowManager' => ['services', 'Pimcore\\Workflow\\Manager', 'getManagerService', true],
            'placeStatusInfo' => ['services', 'Pimcore\\Workflow\\Place\\StatusInfo', 'getStatusInfoService', true],
            'router' => ['services', 'router', 'getRouterService', false],
            'actionsButtonService' => ['privates', 'Pimcore\\Bundle\\AdminBundle\\Service\\Workflow\\ActionsButtonService', 'getActionsButtonServiceService', true],
        ], [
            'workflowManager' => 'Pimcore\\Workflow\\Manager',
            'placeStatusInfo' => 'Pimcore\\Workflow\\Place\\StatusInfo',
            'router' => '?',
            'actionsButtonService' => 'Pimcore\\Bundle\\AdminBundle\\Service\\Workflow\\ActionsButtonService',
        ]))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\WorkflowController::getWorkflowDetailsStore()', $container);
    }
}
