<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflowControllersubmitWorkflowTransitionActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ls0TEQL.Pimcore\Bundle\AdminBundle\Controller\Admin\WorkflowController::submitWorkflowTransitionAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ls0TEQL.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\WorkflowController::submitWorkflowTransitionAction()'] = ($container->privates['.service_locator.Ls0TEQL'] ?? $container->load('get_ServiceLocator_Ls0TEQLService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\WorkflowController::submitWorkflowTransitionAction()', $container);
    }
}
