<?php

namespace ContainerBEOUcSK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflowControllershowGraphService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TsIruTl.Pimcore\Bundle\AdminBundle\Controller\Admin\WorkflowController::showGraph()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TsIruTl.Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\WorkflowController::showGraph()'] = ($container->privates['.service_locator.TsIruTl'] ?? $container->load('get_ServiceLocator_TsIruTlService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\WorkflowController::showGraph()', $container);
    }
}
